# Generated by Django 4.2.3 on 2024-08-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
